In [1]:
import numpy as np

In [2]:
np1=np.arange(10)
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np0=np.zeros((2,5),dtype='int32')
np0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
np0=np.zeros((3,3))
np0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np1=np.ones((2,5),dtype='int32')
np1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np1=np.ones((3,3))
np1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1=np.arange(20)
print('array1:\n',array1)

array2=array1.reshape(-1,5)
print('array2:\n',array2)

array3=array1.reshape(-1,10)
print('array3:\n',array3)

array4=array1.reshape(10,-1)
print('array4: \n',array4)

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array3:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
array4: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [2]:
import numpy as np
array1=np.arange(8)
print("array1",array1.tolist())

array3d=array1.reshape(2,2,2)
print("array3d",array3d.tolist())

array2d=array3d.reshape(-1,1)
print("array2d",array2d.tolist())

array6=array1.reshape(-1,1)
print("array6",array6.tolist())

array1 [0, 1, 2, 3, 4, 5, 6, 7]
array3d [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array2d [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 [[0], [1], [2], [3], [4], [5], [6], [7]]
